# Ejercicio día 8
**Programación I**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [1]:
import numpy as np

In [303]:
filas=10
colum=10
a=np.zeros([filas*colum]) #Creo un array de ceros
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [304]:
b=np.arange(filas*colum) #Obtengo un arange entre 0 y el número de filasxcolumnas
c=np.random.choice(b,int(filas*colum/2),replace=False) 
#Que escoja la mitad de los números en b 
#Replace False significa que no puede agarrar un número que ya agarró
print(c)

[55 85 13 27 35 74 46 86  1 33 91 87 99 17  4  5 82 50 51 92 76 65 57 71
 60 31 49 23 24 19 64 45  6 84 94 32 18 80 41 44 81 28  8 15 96 22 43 61
 78 56]


In [305]:
a[c]=1 #En mi aray inicial le inserto las posiciones aleatorias =1
a

array([0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1.])

In [307]:
a.resize(filas,colum) #Ajusto el aray para que sea de tamaño filas x columnas
a

array([[0., 1., 0., 0., 1., 1., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 1., 1., 1.],
       [0., 0., 1., 1., 1., 0., 0., 1., 1., 0.],
       [0., 1., 1., 1., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 1., 1., 0., 0., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 0., 1., 1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1., 0., 1., 0., 0., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



In [189]:
# INCISO 1
matriz1=np.zeros((5,2)) #hago una matriz de ceros
matriz2=np.ones((5,2)) #hago una matriz de unos
print(matriz1)
print(matriz2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
vc1=matriz1.flatten() #Defino una variable que junte todos los elementos en una fila
vc1
columna1=vc1[:,None] #Le pido que me convierta la fila en columna
columna1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [41]:
vc2=matriz2.flatten()
columna2 = vc2[:,None]
columna2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [198]:
# INCISO 2
apilacion = np.dstack((columna1,columna2)) #dstack me genera un espejo de 0s y 1s a lo largo de tecera dimensión.
apilacion

array([[[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]]])

In [195]:
# INCISO 3
fila1 = matriz1.flatten() #Le pido que me lo saque en una fila
fila1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [196]:
fila2=matriz2.flatten()
fila2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [155]:
np.concatenate((fila1[:,None],fila2[:,None]),axis=0) #Concateno las filas en columna, una abajo de otra.

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una matriz. 

In [65]:
#INCISO 1
matriz = np.random.randint(10,size=(3,3)) #Creo una matriz que me genere números enteros aleatorios
matriz 
#El número 10 se refiere a que saca números aleatorios de 0 a 9
#Size se refiere al tamaño de la matriz: 3 filas y 3 columnas

array([[5, 2, 3],
       [6, 4, 8],
       [2, 6, 5]])

In [66]:
#INCISO 2
def f(matriz):
    return 2*(matriz[:,0])+3*(matriz[:,1])+(matriz[:,2])**2

#Definimos la función en donde le pedimos que la x sea toda la primera columna, y, toda la segunda columna
#z es la última columna.

In [147]:
funcion = f(matriz) #Nos devuelve la función aplicada a todas las x, y, z por fila
funcion[:,None] #Nos devuelve el resultado anterior en columnas

array([[25],
       [88],
       [47]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [283]:
cuadrado = np.random.randint(0,2,([50,50])) 
#Le pido que me de números aleatorios entre 0 y 1 en mi cuadrado principal de 50x50
cuadrado

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 1, 1]])

In [284]:
cuadrado2 = cuadrado[20:40,20:40] #Le pido que me de mi cuadrado del centro de 20x20
cuadrado2

array([[0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 1, 0,

In [285]:
areaC1=sum(cuadrado.flatten()) #El área del cuadrado principal es la suma de todos los 1s
areaC1

1221

In [286]:
areaC2=sum(cuadrado2.flatten()) #El área del segundo cuadrado es la suma de los 1s dentro de ese cuadrado
areaC2

189

In [287]:
area=(areaC2/areaC1) #la proporción del área del cuadrado 2 entre el cuadrado 1
area

0.1547911547911548

In [288]:
area*2500 #El área de mi cuadrado 20x20

386.977886977887

In [289]:
50*50

2500

In [290]:
20*20

400

In [291]:
400/2500

0.16

***
# *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

## 1. 73 funciones

In [314]:
#1. empty
uno = np.empty((2,3),dtype=float,order="C") #Me devuelve un array sin entradas
uno

array([[0.9721683 , 0.63463176, 0.13738979],
       [0.64458448, 0.1743549 , 0.21517447]])

In [348]:
#2. empty like
ex=np.array([[1,2,3],[4,5,6]])
print(ex)
dos = np.empty_like(ex,dtype=bool) #Me devuelve un array con la forma de otro array que ya tengo
dos

[[1 2 3]
 [4 5 6]]


array([[False, False, False],
       [False, False, False]])

In [326]:
#3.eye
eye = np.eye(3,k=0) #Me devuelve unos en la diagonal, el resto es ceros
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [323]:
#4. identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [329]:
#5. ones
np.ones([5,5]) #Me devuelve una matriz de unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [338]:
#6. ones like
x = np.arange(3)
print(x)
np.ones_like(x)#Devuelve una matriz de unos igual a la anterior

[0 1 2]


array([1, 1, 1])

In [339]:
# 7. zeros
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [347]:
# 8. zeros like
y=np.array([[1,2],[3,4]])
print(y)
np.zeros_like(y) #Me devuelve en una matriz los ceros como alguna variable

[[1 2]
 [3 4]]


array([[0, 0],
       [0, 0]])

In [345]:
#9. full
np.full((2,2),"X")#Me devuelve in valor fijo

array([['X', 'X'],
       ['X', 'X']], dtype='<U1')

In [354]:
#10. full like
z=np.arange(6)
print(z)
np.full_like(z,9)

[0 1 2 3 4 5]


array([9, 9, 9, 9, 9, 9])

In [356]:
#11. array
np.array([[1,2],[9,10],[11,15]])

array([[ 1,  2],
       [ 9, 10],
       [11, 15]])

In [357]:
#12. as array
e=[1,5]
np.asarray(e)

array([1, 5])

In [359]:
#13. as any array
f=[1,1,3]
np.asanyarray(f)

array([1, 1, 3])

In [361]:
#14. as contiguous array
g=np.arange(6).reshape(3,2)
np.ascontiguousarray(g)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [364]:
#15. as matrix
h=np.array([[3,1],[4,1]])
print(h)
np.asmatrix(h)

[[3 1]
 [4 1]]


matrix([[3, 1],
        [4, 1]])

In [367]:
#16. copy
i=np.array([3,6,9])
j=np.copy(i)
i[0]=2
i[0]==j[0]

False

In [375]:
#17. from buffer
np.frombuffer(b'\x04\x06',dtype=np.uint8)

array([4, 6], dtype=uint8)

In [571]:
#18. l strip
x = np.array(["adrian","alberto","angelica"])
np.char.lstrip(x,"a") #le quita el primer caracter al que tenga la a

array(['drian', 'lberto', 'ngelica'], dtype='<U8')

In [394]:
#19. from function
np.fromfunction(lambda x, y: x+y, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [396]:
#20. from iter
itera=(x+x for x in range(9))
np.fromiter(itera,int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [402]:
#21. from string
np.fromstring("9,9,9",dtype=int,sep=", ")

array([9, 9, 9])

In [564]:
#22. upper string
x=["coca","pepsi","fanta"]
np.char.upper(x)

array(['COCA', 'PEPSI', 'FANTA'], dtype='<U5')

In [403]:
#23. arange
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [406]:
#24. linspace
np.linspace(1.5,6.5,num=6) #devuelve valores espaciados en un intervalo

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5])

In [407]:
#25. logspace
np.logspace(5,10,num=3) #devuelve valores separados en escala logarítmica

array([1.00000000e+05, 3.16227766e+07, 1.00000000e+10])

In [408]:
#26. geomspace
np.geomspace(1,10,num=5)#devuelve en escala geométrica progresiva

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [410]:
#27. mgrid
np.mgrid[0:3,0:5] #junta dos matrices

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [412]:
#28. diag
m=np.arange(16).reshape(4,4)
print(m)
np.diag(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

In [413]:
#29. diagflat
np.diagflat([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [414]:
#30. tri
np.tri(4,4) #da la diagonal inferior de 1s

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [421]:
#31. tril da la diagonal inferior
np.tril([[2,4,6],[8,9,1],[4,5,6]])

array([[2, 0, 0],
       [8, 9, 0],
       [4, 5, 6]])

In [422]:
#32. triu da la diagonal superior
np.triu([[2,4,6],[8,9,1],[4,5,6]])

array([[2, 4, 6],
       [0, 9, 1],
       [0, 0, 6]])

In [424]:
#33. mat: interpreta el input como matriz
np.mat([[2,3],[6,5],[4,3]])

matrix([[2, 3],
        [6, 5],
        [4, 3]])

In [428]:
#34. bmat
A = np.mat('1 2 3; 3 4 5')
B = np.mat('5 6 7; 7 8 9')
np.bmat([A, B]) #devuelve una matriz a partir de un string

matrix([[1, 2, 3, 5, 6, 7],
        [3, 4, 5, 7, 8, 9]])

In [435]:
#35. shape
v=np.array([[1,2],[3,4]])
print(v)
np.shape(v)

[[1 2]
 [3 4]]


(2, 2)

In [437]:
# 36. reshape
v=np.array([[1,2],[3,4],[5,6]])
print(v)
v.reshape(2,3)

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [438]:
# 37. ravel
f= np.array([[3,3],[4,5],[8,9]])
f.ravel() #me lo devuelve en lista

array([3, 3, 4, 5, 8, 9])

In [441]:
#38. flat
x = np.arange(1, 10).reshape(3, 3)
print(x)
print(x.flat[3])
print(x.T)
print(x.T.flat[3])
#devuelve la posición como si fuera la posición de una lista

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
[[1 4 7]
 [2 5 8]
 [3 6 9]]
2


In [442]:
#39. flatten
y=np.arange(0,15).reshape(5,3) #me lo devuelve en una sola lista
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [455]:
#40. move axis
z = np.zeros((2,4, 5))
print(z)
print(np.moveaxis(z, 0, -1).shape) #mueve todos los índices de lo que va en la matriz.

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(4, 5, 2)


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [460]:
#41. roll axis
aa = np.ones((1,2,3,4))
np.rollaxis(aa, 3, 1).shape #mueve la posición 3 a la 1
np.rollaxis(aa,2,1).shape

(1, 3, 2, 4)

In [468]:
#42. swap axis
bb = np.array([[[0,3],[4,3]],[[5,6],[9,9]]])
print(bb)
np.swapaxes(bb,0,2) #si es 1 cambia filas y si es 2 cambia columnas

[[[0 3]
  [4 3]]

 [[5 6]
  [9 9]]]


array([[[0, 5],
        [4, 9]],

       [[3, 6],
        [3, 9]]])

In [476]:
#43. transpuesta
cc = np.array([[1,3],[4,5]])
cc
cc.T

array([[1, 4],
       [3, 5]])

In [479]:
#44. at least 1D
np.atleast_1d([1,2]) #devuelve el array en 1D

array([1, 2])

In [484]:
#45. at least 2D
print(np.atleast_2d([1,2])) #devuelve en 2D
np.atleast_2d([1,2]).shape

[[1 2]]


(1, 2)

In [483]:
#46. at least 3D
print(np.atleast_3d([1,2]))
np.atleast_3d([1,2]).shape

[[[1]
  [2]]]


(1, 2, 1)

In [570]:
#47. expand dims
dd = np.array([3,3])
dd
ee=np.expand_dims(dd,axis=0) #hace una mayor dimensión, si es 1 es por columna y si es 0 es por fila.
ee

array([[3, 3]])

In [491]:
#48. as scalar
np.asscalar(np.array([100])) #devuelve un escalar

100

In [496]:
#49. concatenate
ff = np.array([[1, 3], [9, 5]])
gg = np.array([[2, 8],[10,11]])
np.concatenate((ff, gg), axis=0) #une 2 arrays

array([[ 1,  3],
       [ 9,  5],
       [ 2,  8],
       [10, 11]])

In [502]:
#50. stack
x = np.array([3,4])
y = np.array([5,7])
np.stack((x, y), axis=-1) #concatena de arriba para abajo cuando es 0 y si es -1 es por columna


array([[3, 5],
       [4, 7]])

In [503]:
#51. column stack
x = np.array((3,4,2))
y = np.array((8,7,5))
np.column_stack((x,y)) #une por columnas

array([[3, 8],
       [4, 7],
       [2, 5]])

In [504]:
#52. d stack
x = np.array((3,4,2))
y = np.array((8,7,5))
np.dstack((x,y)) #concatena along another axis, lo vuelve en tercera dimensión, es como un espejo.

array([[[3, 8],
        [4, 7],
        [2, 5]]])

In [505]:
#53. h stack
x = np.array((3,4,2)) #lo devuelve de forma horizontal
y = np.array((8,7,5))
np.hstack((x,y))

array([3, 4, 2, 8, 7, 5])

In [506]:
#54. v stack
x = np.array((3,4,2))
y = np.array((8,7,5))
np.vstack((x,y)) #lo devuelve en forma vertical: por filas

array([[3, 4, 2],
       [8, 7, 5]])

In [509]:
#55. split
x = np.arange(15)
np.split(x,3) #los separa de acuerdo al índice q uno ponga

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [510]:
#56. array split
x = np.arange(8.0)
np.array_split(x, 6) #me agrupa como yo quiera

[array([0., 1.]),
 array([2., 3.]),
 array([4.]),
 array([5.]),
 array([6.]),
 array([7.])]

In [526]:
#57. d split
x = np.arange(16).reshape(2, 2, 4)
print(x)

np.dsplit(x, 2)
#lo divide en subarrays a lo largo de la tercera dimensión.

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]), array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [528]:
#58. h split
x = np.arange(20).reshape(5,4)
print(x)
np.hsplit(x,2) #lo divide horizontalmente, dos bloques que están uno a la par

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [531]:
#59. v split
x = np.arange(20).reshape(5,4)
print(x)
np.vsplit(x,5) #lo divide verticalmente

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [533]:
#60. tile
y = np.array(["A","B","C"])
np.tile(y, 2)#me repite un número de veces mi array
np.tile(y,4)

array(['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
      dtype='<U1')

In [534]:
#61. repeat
np.repeat("+", 10) #me repite el símbolo 10 veces

array(['+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], dtype='<U1')

In [537]:
#62. delete
x = np.array([[5,5,5], [7,7,7], [9,9,9]])
print(x)
np.delete(x, 2, 1)#me elimina 0:fila o 1:columna

[[5 5 5]
 [7 7 7]
 [9 9 9]]


array([[5, 5],
       [7, 7],
       [9, 9]])

In [561]:
#63. append
x=np.array([[1,2,3],[3,4,5]])
np.append(x,[[1,1,1],[4,5,4],[3,2,1]],axis=0) #me agrega valores

array([[1, 2, 3],
       [3, 4, 5],
       [1, 1, 1],
       [4, 5, 4],
       [3, 2, 1]])

In [546]:
#64. resize
X=np.array([[0,1],[2,3]])
print(X)
np.resize(X,(3,3)) #para cambiarle el tamaño y en los espacios donde hay cero es donde no había nada

[[0 1]
 [2 3]]


array([[0, 1, 2],
       [3, 0, 1],
       [2, 3, 0]])

In [547]:
#65. trim zeros
np.trim_zeros([0, 0,0,0,0,0,9]) #quitarle los ceros a una lista.

[9]

In [548]:
#66. flip
X=np.array([[0,1],[2,3]])
print(X)
np.flip(X) #pone al reves todas las posiciones.

[[0 1]
 [2 3]]


array([[3, 2],
       [1, 0]])

In [550]:
#67. flipr
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
np.fliplr(x) #lo voltea de derecha a izquierda

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [551]:
#68. flipud
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
np.flipud(x) #lo voltea de abajo para arriba.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [553]:
#69. reshape
print(np.arange(21))
x = np.arange(21).reshape((7,3))
x #le cambia de forma

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [554]:
#70. rot 90
x = np.array([[5,5,5],[9,9,9]])
x

np.rot90(x) #lo voltea 90 grados


array([[5, 9],
       [5, 9],
       [5, 9]])

In [556]:
#71. add
np.char.add("choco","late") #suma los strings

array('chocolate', dtype='<U9')

In [557]:
#72. multiply
np.char.multiply("pipi",6)

array('pipipipipipipipipipipipi', dtype='<U24')

In [568]:
#73. capitalize
x = np.array(["adrian","sofia","nicolle"])
np.char.capitalize(x)

array(['Adrian', 'Sofia', 'Nicolle'], dtype='<U7')

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)

In [ ]:
#Archivo NPY: es para un array

In [594]:
x = np.array([[1,3,5,7,9],[2,4,6,8,10]]) #defino un array
np.save("binario.npy", x) #lo guardo con este nombre, el array que definí como x 

In [595]:
y=np.load('binario.npy') #para cargar el archivo

In [596]:
y

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
#Archivo NPZ: es para varios arrays

In [604]:
w=np.array([2,3,4])
v=np.array([5,6,7])
np.savez("binario.npz",objetow=w,objetov=v)#Le doy nombres a cada array tipo diccionario

In [605]:
z=np.load("binario.npz") #para cargar ambos arrays

In [606]:
z["objetow"]#le pido que me de el primer array como un diccionario

array([2, 3, 4])

In [607]:
z["objetov"] #le pido el segundo array

array([5, 6, 7])

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files) 

In [581]:
a = np.array([1, 2, 3, 4])
np.savetxt('texto1.txt', a, fmt='%f') #me guarda el texto con el array "a" y con formato float
b = np.loadtxt('texto1.txt', dtype=int) #me carga un archivo

In [582]:
a

array([1, 2, 3, 4])

In [583]:
b

array([1, 2, 3, 4])

In [584]:
c=np.loadtxt('mg.txt',dtype=float)#en un archivo txt creado en la misma carpeta
#pongo el nombre, y el tipo para que me cargue.

In [585]:
c

array([5.5, 6.3, 5.1, 6.7, 5.8, 6. ])

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [620]:
matriztot=np.random.randint((10),size=[7,7])#genero matriz con números random con 7 filas y columnas
matriztot

array([[8, 0, 8, 4, 8, 7, 2],
       [9, 9, 9, 6, 4, 1, 5],
       [2, 0, 2, 2, 4, 7, 4],
       [8, 6, 1, 4, 4, 1, 5],
       [0, 1, 7, 1, 3, 3, 6],
       [9, 9, 9, 8, 2, 3, 4],
       [4, 7, 8, 8, 8, 7, 9]])

In [625]:
np.savetxt("MCO.csv",matriztot,delimiter=",")#Guardo en un archivo csv la matriz delimitado por comas

In [626]:
archivoCSV=np.loadtxt('MCO.csv',delimiter=',')#para cargar el archivo csv
archivoCSV

array([[8., 0., 8., 4., 8., 7., 2.],
       [9., 9., 9., 6., 4., 1., 5.],
       [2., 0., 2., 2., 4., 7., 4.],
       [8., 6., 1., 4., 4., 1., 5.],
       [0., 1., 7., 1., 3., 3., 6.],
       [9., 9., 9., 8., 2., 3., 4.],
       [4., 7., 8., 8., 8., 7., 9.]])

In [627]:
matrizX=archivoCSV[::,:6] #Defino mi matriz X a partir del archivo CSV que son las primeras 6 columnas
matrizX

array([[8., 0., 8., 4., 8., 7.],
       [9., 9., 9., 6., 4., 1.],
       [2., 0., 2., 2., 4., 7.],
       [8., 6., 1., 4., 4., 1.],
       [0., 1., 7., 1., 3., 3.],
       [9., 9., 9., 8., 2., 3.],
       [4., 7., 8., 8., 8., 7.]])

In [628]:
matrizY=matriztot[::,6]
matrizY
matrizYcolum=matrizY[:,None] #defino mi vector columna y
matrizYcolum

array([[2],
       [5],
       [4],
       [5],
       [6],
       [4],
       [9]])

In [629]:
XTrans=matrizX.T #Le saco la transpuesta a la matriz X
XTrans

array([[8., 9., 2., 8., 0., 9., 4.],
       [0., 9., 0., 6., 1., 9., 7.],
       [8., 9., 2., 1., 7., 9., 8.],
       [4., 6., 2., 4., 1., 8., 8.],
       [8., 4., 4., 4., 3., 2., 8.],
       [7., 1., 7., 1., 3., 3., 7.]])

In [630]:
XTporX=(XTrans@matrizX) #multiplicación matricial X transpuesta por X
XTporX

array([[310., 238., 270., 226., 190., 142.],
       [238., 248., 231., 207., 137.,  94.],
       [270., 231., 344., 237., 215., 184.],
       [226., 207., 237., 201., 163., 135.],
       [190., 137., 215., 163., 189., 163.],
       [142.,  94., 184., 135., 163., 167.]])

In [632]:
Beta=np.linalg.inv(XTporX)@XTrans@matrizYcolum #Defino mi BETA
Beta

array([[-0.39850179],
       [ 1.66785559],
       [ 0.07749225],
       [-1.54753546],
       [ 0.63786303],
       [ 0.8113525 ]])

In [633]:
resultadoY=matrizX@Beta #el resutlado de Y
resultadoY

array([[2.02415361],
       [6.19920631],
       [4.49382964],
       [4.06927423],
       [5.0104125 ],
       [3.45111435],
       [9.10300803]])

In [635]:
def estimacionMCO(): #AHORA solo lo convierto en función
    archivoCSV=np.loadtxt('MCO.csv',delimiter=',')
    matrizX=archivoCSV[::,:6]
    matrizY=matriztot[::,6]
    matrizYcolum=matrizY[:,None]
    XTrans=matrizX.T
    XTporX=(XTrans@matrizX)
    Beta=np.linalg.inv(XTporX)@XTrans@matrizYcolum
    resultadoY=matrizX@Beta
    return resultadoY

In [636]:
estimacionMCO() #Me da el resultado

array([[2.02415361],
       [6.19920631],
       [4.49382964],
       [4.06927423],
       [5.0104125 ],
       [3.45111435],
       [9.10300803]])